name: production

on:
  push:
    tags: "*"

jobs:
  build:
    runs-on: ubuntu-latest
    container: golang:1.13
    steps:
    - uses: actions/checkout@v2
    - name: Bootstrap
      run: |
        apt-get update
        apt-get install -y zip awscli
    - name: Build and zip
      run: |
        GOOS=linux go build -o main .
        zip -r ./function.zip main
    - name: deploy zip to lambda
      run: |
        aws lambda update-function-code --function-name key-resolve-production --zip-file fileb://function.zip --publish
      env:
        AWS_DEFAULT_REGION: eu-west-1
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
